name: frostiq
description: Smart Refrigerator Monitoring
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.2.2
  mobile_scanner: ^5.1.1
  http: ^1.2.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  app_links: ^6.1.1   # For handling deep links (frostiq://)
  google_generative_ai: ^0.4.5 # For Gemini AI analysis

flutter:
  uses-material-design: true